import { AlertTriangle, BarChart3, CarFront, CheckCircle2, ShieldCheck, Users } from "lucide-react";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getServerLang } from "@/lib/i18n/lang-server";
import { t } from "@/lib/i18n/dictionary";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import { moderateVehicle, resolveDisputeAction, reviewIdVerification, signOutAdmin } from "./actions";

export default async function AdminPage(){
 const lang=await getServerLang();
 const supabase=await createClient();
 const {data:{user}}=await supabase.auth.getUser();
 if(!user) redirect("/login");
 const {data:isAdmin}=await supabase.rpc("kerreore_is_admin");
 if(!isAdmin) redirect("/dashboard");
 const {data:vehicles}=await supabase.from("kerreore_vehicles").select("id,make,model,year,owner_id,hourly_rate,published,created_at").order("created_at",{ascending:false});
 const {count:users}=await supabase.from("kerreore_profiles").select("id",{count:"exact",head:true});
 const {data:pendingIds}=await supabase.from("kerreore_profiles").select("id,full_name,id_document_path").eq("id_verification_status","pending");
 const {data:openDisputes}=await supabase.from("kerreore_bookings").select("id,dispute_reason,starts_at,total_amount,kerreore_vehicles(make,model)").eq("dispute_status","open");
 const listed=(vehicles??[]).filter(v=>v.published).length; const review=(vehicles??[]).filter(v=>!v.published).length;
 return <main className="min-h-screen bg-[#f7f7f4]"><header className="border-b border-black/8 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><a href="/" className="text-2xl font-black tracking-[-.06em]">kerreore<span className="text-lime-500">.</span></a><div className="flex items-center gap-3"><LanguageSwitcher/><span className="rounded-full bg-black px-3 py-1.5 text-xs font-black text-white">ADMIN</span><form action={signOutAdmin}><button className="rounded-full border border-black/10 px-4 py-2.5 text-sm font-bold">{t(lang,"admin_sign_out")}</button></form></div></div></header><section className="mx-auto max-w-7xl px-5 py-10 md:px-8"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-black/40">{t(lang,"admin_operations")}</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em]">{t(lang,"admin_title")}</h1><p className="mt-3 text-black/50">{t(lang,"admin_subtitle")}</p></div><ShieldCheck size={36}/></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Users,String(users??0),t(lang,"admin_stat_users")],[CarFront,String(listed),t(lang,"admin_stat_published")],[BarChart3,String(vehicles?.length??0),t(lang,"admin_stat_total")],[AlertTriangle,String(review),t(lang,"admin_stat_review")]].map(([I,v,l])=>{const Icon=I as typeof Users;return <div key={l as string} className="rounded-3xl border border-black/8 bg-white p-6"><Icon size={21}/><p className="mt-5 text-3xl font-black">{v as string}</p><p className="mt-1 text-sm text-black/45">{l as string}</p></div>})}</div>

<div className="mt-8 rounded-3xl border border-black/8 bg-white p-6"><h2 className="text-xl font-black">{t(lang,"admin_id_review_title")}</h2><div className="mt-5 space-y-3">{(pendingIds??[]).map(p=><div key={p.id} className="flex items-center justify-between rounded-2xl bg-[#f7f7f4] p-4"><div><p className="font-black">{p.full_name||p.id}</p><p className="mt-1 text-xs text-black/45 font-mono">{p.id_document_path}</p></div><div className="flex gap-2"><form action={reviewIdVerification}><input type="hidden" name="user_id" value={p.id}/><input type="hidden" name="approve" value="true"/><button className="rounded-full bg-black px-3 py-1.5 text-xs font-black text-white">{t(lang,"admin_id_approve")}</button></form><form action={reviewIdVerification}><input type="hidden" name="user_id" value={p.id}/><input type="hidden" name="approve" value="false"/><button className="rounded-full border border-red-200 px-3 py-1.5 text-xs font-bold text-red-700">{t(lang,"admin_id_reject")}</button></form></div></div>)}{!pendingIds?.length&&<div className="py-6 text-center text-sm text-black/45">{t(lang,"admin_id_none")}</div>}</div></div>

<div className="mt-8 rounded-3xl border border-black/8 bg-white p-6"><h2 className="text-xl font-black">{t(lang,"admin_disputes_title")}</h2><div className="mt-5 space-y-3">{(openDisputes??[]).map((d:any)=><div key={d.id} className="rounded-2xl bg-[#f7f7f4] p-4"><p className="font-black">{d.kerreore_vehicles?.make} {d.kerreore_vehicles?.model} \u00b7 \u20ac{d.total_amount}</p><p className="mt-1 text-sm text-black/60">{d.dispute_reason}</p><form action={resolveDisputeAction} className="mt-3 flex gap-2"><input type="hidden" name="booking_id" value={d.id}/><input name="resolution" placeholder={t(lang,"admin_dispute_resolution_ph")} className="flex-1 rounded-xl border border-black/10 bg-white p-2.5 text-sm"/><button className="rounded-xl bg-black px-4 py-2 text-xs font-black text-white">{t(lang,"admin_dispute_resolve")}</button></form></div>)}{!openDisputes?.length&&<div className="py-6 text-center text-sm text-black/45">{t(lang,"admin_disputes_none")}</div>}</div></div>

<div className="mt-8 rounded-3xl border border-black/8 bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{t(lang,"admin_moderation_title")}</h2><span className="text-sm font-bold text-black/45">{t(lang,"admin_moderation_subtitle")}</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-black/8 text-xs uppercase tracking-wider text-black/40"><tr><th className="pb-3">{t(lang,"admin_th_vehicle")}</th><th className="pb-3">{t(lang,"admin_th_owner")}</th><th className="pb-3">{t(lang,"admin_th_rate")}</th><th className="pb-3">{t(lang,"admin_th_status")}</th><th className="pb-3">{t(lang,"admin_th_action")}</th></tr></thead><tbody>{(vehicles??[]).map(v=><tr key={v.id} className="border-b border-black/6 last:border-0"><td className="py-4 font-black">{v.make} {v.model} <span className="font-normal text-black/40">{v.year}</span></td><td className="py-4 text-xs text-black/55">{v.owner_id}</td><td className="py-4">\u20ac{v.hourly_rate}/h</td><td className="py-4"><span className={`rounded-full px-3 py-1 text-xs font-black ${v.published?"bg-green-100 text-green-800":"bg-yellow-100 text-yellow-800"}`}>{v.published?t(lang,"admin_published"):t(lang,"admin_pending")}</span></td><td className="py-4"><form action={moderateVehicle}><input type="hidden" name="vehicle_id" value={v.id}/><input type="hidden" name="published" value={v.published?"false":"true"}/><button className={v.published?"rounded-full border border-black/10 px-3 py-1.5 text-xs font-bold":"rounded-full bg-black px-3 py-1.5 text-xs font-bold text-white"}>{v.published?t(lang,"admin_unpublish"):t(lang,"admin_approve")}</button></form></td></tr>)}</tbody></table>{!vehicles?.length&&<div className="py-12 text-center text-sm text-black/45">{t(lang,"admin_no_listings")}</div>}</div></div><div className="mt-5 flex items-center gap-2 text-xs font-semibold text-black/45"><CheckCircle2 size={15}/> {t(lang,"admin_footer_note")}</div></section></main>}
