"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, XCircle } from "lucide-react";
import { createClient } from "@/lib/supabase/browser";
import { useLang } from "@/lib/i18n/lang-client";
import { t } from "@/lib/i18n/dictionary";
import { translateError } from "@/lib/i18n/errors";
import LanguageSwitcher from "@/components/LanguageSwitcher";
const KOSOVO_TZ = "Europe/Belgrade";
export default function MyBookings(){const lang=useLang();const supabase=createClient();const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[msg,setMsg]=useState("");async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return}const{data}=await supabase.from("kerreore_bookings").select("id,starts_at,ends_at,total_amount,status,kerreore_vehicles(make,model,location)").eq("renter_id",user.id).order("starts_at",{ascending:false});setRows(data??[]);setLoading(false)}useEffect(()=>{load()},[]);async function cancel(id:string){const{error}=await supabase.rpc("kerreore_update_booking_status",{p_booking_id:id,p_status:"cancelled"});if(error)setMsg(translateError(error.message,lang));load()}if(loading)return <main className="grid min-h-screen place-items-center">{t(lang,"car_loading")}</main>;return <main className="min-h-screen bg-[#f7f7f4]"><header className="border-b border-black/8 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-5"><Link href="/" className="flex items-center gap-2 text-sm font-bold"><ArrowLeft size={16}/> {t(lang,"nav_home")}</Link><div className="flex items-center gap-3"><LanguageSwitcher/><Link href="/cars" className="rounded-full border border-black/10 px-4 py-2 text-sm font-bold">{t(lang,"nav_browse")}</Link></div></div></header><section className="mx-auto max-w-5xl px-5 py-10"><p className="text-xs font-black uppercase tracking-[.18em] text-black/40">{t(lang,"bookings_label")}</p><h1 className="mt-2 text-4xl font-black">{t(lang,"bookings_title")}</h1>{msg&&<p className="mt-5 rounded-2xl bg-[#f5f5f0] p-4 text-sm font-bold">{msg}</p>}<div className="mt-8 space-y-3">{rows.map(b=><div key={b.id} className="rounded-3xl border border-black/8 bg-white p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="font-black">{b.kerreore_vehicles?.make} {b.kerreore_vehicles?.model}</p><p className="mt-1 text-sm text-black/50">{new Date(b.starts_at).toLocaleString([], {timeZone: KOSOVO_TZ})} \u2192 {new Date(b.ends_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",timeZone: KOSOVO_TZ})}</p><p className="mt-1 text-xs text-black/40">\u00b7 \u20ac{b.total_amount}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-[#f5f5f0] px-3 py-1.5 text-xs font-black">{t(lang,`status_${b.status}`)}</span>{(b.status==='pending'||b.status==='confirmed')&&<button onClick={()=>cancel(b.id)} className="rounded-full border border-red-200 px-3 py-2 text-xs font-bold text-red-700"><XCircle className="mr-1 inline" size={14}/> {t(lang,"bookings_cancel")}</button>}</div></div></div>)}{!rows.length&&<div className="rounded-3xl border border-dashed border-black/15 bg-white p-12 text-center text-sm text-black/45">{t(lang,"bookings_none")} <Link href="/cars" className="font-bold underline">{t(lang,"bookings_browse")}</Link></div>}</div></section></main>}
