"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/browser";

const friendlyAuthError=(message:string)=>{
  const m=message.toLowerCase();
  if(m.includes("rate limit")||m.includes("too many requests")) return "Too many email requests. Please wait before requesting another confirmation or reset email.";
  if(m.includes("invalid login credentials")) return "Email or password is incorrect. If you already have an account, use Sign in or Forgot password instead of creating another account.";
  return message;
};

export default function LoginPage(){
  const[mode,setMode]=useState<"login"|"signup">("login");
  const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[name,setName]=useState("");const[error,setError]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[cooldown,setCooldown]=useState(0);
  function startCooldown(seconds=30){setCooldown(seconds);const timer=window.setInterval(()=>setCooldown(v=>{if(v<=1){window.clearInterval(timer);return 0}return v-1}),1000)}
  async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError("");setMessage("");const supabase=createClient();
    if(mode==="login"){const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(friendlyAuthError(error.message));setBusy(false);return}const{data:profile}=await supabase.from("kerreore_profiles").select("role").eq("id",data.user.id).single();window.location.href=profile?.role==="provider"?"/provider":profile?.role==="admin"?"/admin":"/dashboard";return}
    const{data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:`${window.location.origin}/auth/callback`}});if(error){setError(friendlyAuthError(error.message));setBusy(false);return}if(data.session){window.location.href="/dashboard";return}setMessage("If this email is new, a confirmation email has been sent. If you already have a Kerreore account, use Sign in or Forgot password instead.");startCooldown();setBusy(false)}
  async function resend(){if(busy||cooldown)return;if(!email){setError("Enter your email address first.");return}setBusy(true);setError("");setMessage("");const{error}=await createClient().auth.resend({type:"signup",email});if(error){setError(friendlyAuthError(error.message))}else{setMessage("If this account needs confirmation, a confirmation email has been sent. Check your inbox and spam folder.");startCooldown()}setBusy(false)}
  async function reset(){if(busy||cooldown)return;if(!email){setError("Enter your email address first.");return}setBusy(true);setError("");setMessage("");const{error}=await createClient().auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/auth/reset-password`});if(error){setError(friendlyAuthError(error.message))}else{setMessage("If an account exists for this email, a password reset email has been sent. Check your inbox and spam folder.");startCooldown()}setBusy(false)}
  return <main className="flex min-h-screen items-center justify-center px-5 py-10"><div className="w-full max-w-md"><a href="/" className="text-3xl font-black tracking-[-.07em]">kerreore<span className="text-lime-500">.</span></a><div className="mt-10 rounded-[2rem] border border-black/8 bg-white p-7 shadow-sm"><div className="mb-7 flex rounded-2xl bg-[#f5f5f0] p-1"><button onClick={()=>{setMode("login");setError("");setMessage("")}} className={`flex-1 rounded-xl py-2.5 text-sm font-black ${mode==="login"?"bg-white shadow-sm":"text-black/45"}`}>Sign in</button><button onClick={()=>{setMode("signup");setError("");setMessage("")}} className={`flex-1 rounded-xl py-2.5 text-sm font-black ${mode==="signup"?"bg-white shadow-sm":"text-black/45"}`}>Create account</button></div><h1 className="text-3xl font-black tracking-[-.05em]">{mode==="login"?"Welcome back":"Join Kerreore"}</h1><p className="mt-2 text-sm text-black/50">{mode==="login"?"Sign in with your Kerreore account.":"Create a secure Kerreore account."}</p><form onSubmit={submit} className="mt-7 space-y-4">{mode==="signup"&&<input value={name} onChange={e=>setName(e.target.value)} required placeholder="Full name" className="w-full rounded-2xl border border-black/10 bg-[#f7f7f4] px-4 py-3.5 outline-none"/>}<input value={email} onChange={e=>setEmail(e.target.value)} required type="email" placeholder="Email address" className="w-full rounded-2xl border border-black/10 bg-[#f7f7f4] px-4 py-3.5 outline-none"/><input value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} type="password" placeholder="Password (8+ characters)" className="w-full rounded-2xl border border-black/10 bg-[#f7f7f4] px-4 py-3.5 outline-none"/>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}{message&&<p className="rounded-xl bg-lime-50 p-3 text-sm font-semibold text-green-800">{message}</p>}<button disabled={busy} className="w-full rounded-2xl bg-black py-3.5 font-black text-white disabled:opacity-50">{busy?"Please wait…":mode==="login"?"Sign in":"Create account"}</button></form>{mode==="login"&&<div className="mt-5 grid gap-2 text-center text-xs"><button disabled={busy||!!cooldown} onClick={reset} className="font-bold underline">{cooldown?`Wait ${cooldown}s`:"Forgot password?"}</button><button disabled={busy||!!cooldown} onClick={resend} className="font-bold underline">{cooldown?`Resend confirmation (${cooldown}s)`:"Resend confirmation email"}</button></div>}<p className="mt-5 text-center text-xs text-black/40">Authentication and sessions are handled by Supabase Auth. Roles are enforced by the database, not browser storage.</p></div></div></main>}
