"use client";
import { useState } from "react";
import { ArrowLeft, CarFront, Check, ImagePlus, MapPin } from "lucide-react";
import Link from "next/link";

export default function NewCarPage() {
  const [saved,setSaved]=useState(false);
  return <main className="min-h-screen"><header className="border-b border-black/8 bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-5"><Link href="/dashboard" className="text-2xl font-black tracking-[-0.06em]">kerreore<span className="text-lime-500">.</span></Link><Link href="/dashboard" className="flex items-center gap-2 text-sm font-bold"><ArrowLeft size={16}/> Cancel</Link></div></header><section className="mx-auto max-w-4xl px-5 py-10 md:py-14"><p className="text-xs font-black uppercase tracking-[0.18em] text-black/40">Owner setup</p><h1 className="mt-2 text-4xl font-black tracking-[-0.05em]">List your car</h1><p className="mt-3 max-w-xl text-black/50">Add the essentials first. This demo saves the listing state locally in the browser.</p><form onSubmit={e=>{e.preventDefault();setSaved(true)}} className="mt-10 space-y-5 rounded-[2rem] border border-black/8 bg-white p-6 md:p-8"><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-bold">Make<input required className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f7f7f4] p-4 outline-none" placeholder="e.g. Volkswagen"/></label><label className="text-sm font-bold">Model<input required className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f7f7f4] p-4 outline-none" placeholder="e.g. Golf 8"/></label><label className="text-sm font-bold">Year<input required type="number" min="1990" max="2030" className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f7f7f4] p-4 outline-none" placeholder="2023"/></label><label className="text-sm font-bold">Price per hour (€)<input required type="number" min="1" className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f7f7f4] p-4 outline-none" placeholder="10"/></label></div><label className="text-sm font-bold">Location<div className="mt-2 flex items-center rounded-2xl border border-black/10 bg-[#f7f7f4] px-4"><MapPin size={17}/><input required className="w-full bg-transparent p-4 outline-none" placeholder="Pristina, Kosovo"/></div></label><div className="rounded-2xl border border-dashed border-black/15 bg-[#f7f7f4] p-8 text-center"><ImagePlus className="mx-auto" size={28}/><p className="mt-3 font-black">Add vehicle photos</p><p className="mt-1 text-sm text-black/45">Storage integration is planned for the production backend.</p></div><button className="w-full rounded-2xl bg-black px-6 py-4 font-black text-white">{saved?<><Check className="mr-2 inline" size={17}/> Listing saved as draft</>:<><CarFront className="mr-1 inline" size={17}/> Save draft</>}</button></form></section></main>;
}
