import { CarFront, CalendarDays, Euro, Plus, TrendingUp } from "lucide-react";

export default function DashboardPage() {
  return <main className="mx-auto min-h-screen max-w-7xl px-5 py-8 md:px-8 md:py-12">
    <header className="mb-10 flex items-center justify-between"><a href="/" className="text-2xl font-black tracking-[-.06em]">kerreore<span className="text-lime-500">.</span></a><div className="flex gap-3"><a href="/bookings" className="rounded-full border border-black/10 bg-white px-4 py-2.5 text-sm font-bold">My bookings</a><a href="/dashboard/cars/new" className="rounded-full bg-black px-4 py-2.5 text-sm font-bold text-white"><Plus className="mr-1 inline" size={15}/> List a car</a></div></header>
    <div className="mb-8"><p className="text-xs font-black uppercase tracking-[.18em] text-black/40">Owner studio</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em]">Good morning, Fadi.</h1><p className="mt-3 text-black/55">Manage your cars, bookings and earnings.</p></div>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Euro,"€1,248","This month"],[CalendarDays,"18","Booked hours"],[CarFront,"2","Active cars"],[TrendingUp,"+24%","vs last month"]].map(([Icon,value,label]) => <div key={label as string} className="rounded-3xl border border-black/8 bg-white p-6"><Icon size={21}/><p className="mt-5 text-3xl font-black">{value as string}</p><p className="mt-1 text-sm text-black/45">{label as string}</p></div>)}</section>
    <section className="mt-8 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-3xl border border-black/8 bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Your cars</h2><a href="/dashboard/cars/new" className="text-sm font-bold">Add car</a></div><div className="mt-5 space-y-3"><div className="flex items-center gap-4 rounded-2xl bg-[#f5f5f0] p-3"><img src="https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=400&q=80" alt="Golf 8" className="h-16 w-24 rounded-xl object-cover"/><div className="flex-1"><p className="font-black">Volkswagen Golf 8</p><p className="text-sm text-black/45">€8 / hour · 4.9 ★</p></div><span className="rounded-full bg-lime-100 px-3 py-1 text-xs font-bold">Active</span></div><div className="flex items-center gap-4 rounded-2xl bg-[#f5f5f0] p-3"><img src="https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=400&q=80" alt="BMW 3 Series" className="h-16 w-24 rounded-xl object-cover"/><div className="flex-1"><p className="font-black">BMW 3 Series</p><p className="text-sm text-black/45">€12 / hour · 4.8 ★</p></div><span className="rounded-full bg-lime-100 px-3 py-1 text-xs font-bold">Active</span></div></div></div><div className="rounded-3xl bg-[#171814] p-7 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-white/45">Next booking</p><h2 className="mt-3 text-2xl font-black">Volkswagen Golf 8</h2><p className="mt-2 text-white/55">Today · 14:00–18:00</p><div className="mt-8 flex items-end justify-between border-t border-white/10 pt-5"><span className="text-sm text-white/45">Expected payout</span><span className="text-2xl font-black">€28</span></div></div></section>
  </main>;
}
